Attribute VB_Name = "M_STATS_DISTRIBUTIONS"

Option Explicit

'==============================================================================
' M_STATS_DISTRIBUTIONS
'------------------------------------------------------------------------------

'
' DESIGN PRINCIPLES
'   - Public worksheet-facing functions return Variant so they can return CVErr.
'   - Private numerical kernels return Double and avoid worksheet-facing overhead.
'   - The fast inverse-normal routine is exposed for Monte Carlo engines.
'   - Invalid domains fail explicitly; they are not silently repaired.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'   - No MsgBox is raised.
'
' NOTES
'   - Lognormal parameters are the mean and standard deviation of Log(X), not of X.
'   - K_STATS_Lognormal_ParametersFromMeanStdDev converts arithmetic mean and standard
'     deviation into log-space parameters.
'   - K_STATS_Normal_InverseCumulativeFast intentionally clips probabilities at the
'     endpoints and returns Double; use it only for validated numerical callers.
'
' UPDATED
'   2026-07-06
'==============================================================================

'==============================================================================
' PRIVATE CONSTANTS
'==============================================================================

Private Const PROB_PI                  As Double = 3.14159265358979
Private Const PROB_TWO_PI              As Double = 6.28318530717959
Private Const PROB_SQRT_TWO_PI         As Double = 2.506628274631
Private Const PROB_INV_SQRT_TWO_PI     As Double = 0.398942280401433
Private Const PROB_EPS                 As Double = 0.000000000000001
Private Const PROB_MAX_EXP             As Double = 709#
Private Const PROB_MIN_EXP             As Double = -745#
Private Const PROB_LARGE_NUMBER        As Double = 1E+100

'
'------------------------------------------------------------------------------
'
'                               NORMAL FAMILY
'
'------------------------------------------------------------------------------
'

' PURPOSE
'   Provides robust normal-family probability distribution functions for
'   worksheet formulas, VBA models and Monte Carlo engines.
'
' WHY THIS EXISTS
'   The normal distribution is the core distribution used in Black-Scholes,
'   value-at-risk examples, regression diagnostics, Gaussian copulas and Monte
'   Carlo simulation. The lognormal distribution is the natural companion for
'   positive variables generated by geometric Brownian motion, including equity
'   prices and other strictly positive market factors.
'
' PUBLIC FUNCTIONS
'   Standard normal:
'     - K_STATS_NormalStandard_Density
'     - K_STATS_NormalStandard_Cumulative
'     - K_STATS_NormalStandard_InverseCumulative
'
'   General normal:
'     - K_STATS_Normal_Density
'     - K_STATS_Normal_Cumulative
'     - K_STATS_Normal_InverseCumulative
'     - K_STATS_Normal_ZScore
'     - K_STATS_Normal_InverseCumulativeFast
'
'   Lognormal:
'     - K_STATS_Lognormal_Density
'     - K_STATS_Lognormal_Cumulative
'     - K_STATS_Lognormal_InverseCumulative
'     - K_STATS_Lognormal_Mean
'     - K_STATS_Lognormal_Variance
'     - K_STATS_Lognormal_ParametersFromMeanStdDev
'
'------------------------------------------------------------------------------
'


Public Function K_STATS_NormalStandard_Density( _
    ByVal Z As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal probability density function at Z.
'
' WHY THIS EXISTS
'   The standard normal density is used in option Greeks, likelihood examples,
'   regression diagnostics and probability-distribution teaching worksheets.
'
' INPUTS
'   Z
'     Standard-normal variate.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Clears the Excel status bar on initialization.
'   - Validates that Z is finite.
'   - Returns Exp(-0.5 * Z^2) / Sqr(2 * Pi).
'
' ERROR POLICY
'   - Non-finite inputs return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' CALLED FROM
'   - Excel worksheet formulas
'   - VBA callers
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message

'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString

'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite input
        If Not PROB_IsFinite(Z) Then
            FailMsg = "Z must be a finite number"
            GoTo Fail_Num
        End If

'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return standard normal density
        K_STATS_NormalStandard_Density = PROB_NormalPDF(Z)
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function

'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function

'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_Density = CVErr(xlErrValue)

End Function


Public Function K_STATS_NormalStandard_Cumulative( _
    ByVal Z As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal cumulative distribution function at Z.
'
' WHY THIS EXISTS
'   The standard normal cumulative distribution is a core building block for
'   Black-Scholes formulas, Gaussian risk-factor models and probability examples.
'
' INPUTS
'   Z
'     Standard-normal variate.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Clears the Excel status bar on initialization.
'   - Validates that Z is finite.
'   - Computes the cumulative probability using a double-precision rational
'     approximation.
'
' ERROR POLICY
'   - Non-finite inputs return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'

'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message

'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString

'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite input
        If Not PROB_IsFinite(Z) Then
            FailMsg = "Z must be a finite number"
            GoTo Fail_Num
        End If

'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return standard normal cumulative probability
        K_STATS_NormalStandard_Cumulative = PROB_NormalCDF(Z)
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function

'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function

'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_NormalStandard_InverseCumulative( _
    ByVal Probability As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function.
'
' WHY THIS EXISTS
'   The inverse standard normal is used to convert probabilities into normal
'   quantiles, for example in VaR, scenario generation and Monte Carlo shocks.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double standard-normal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Clears the Excel status bar on initialization.
'   - Validates that Probability is finite and strictly inside (0, 1).
'   - Uses Peter J. Acklam's rational approximation.
'
' ERROR POLICY
'   - Invalid probabilities return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsValidProbabilityOpen
'   - PROB_NormalInvCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message
'
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
'
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return inverse standard normal cumulative probability
        K_STATS_NormalStandard_InverseCumulative = PROB_NormalInvCDF(Probability)
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_Density( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the normal probability density function at X.
'
' WHY THIS EXISTS
'   Many risk, pricing and statistical models require normal densities with a
'   configurable mean and standard deviation, not only the standard normal case.
'
' INPUTS
'   X
'     Evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite X, Mean and StdDev.
'   - Validates positive StdDev.
'   - Standardizes X into Z = (X - Mean) / StdDev.
'   - Returns StandardNormalDensity(Z) / StdDev.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_ValidateNormalInputs
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized variate
    Dim FailMsg             As String          'Detailed failure message
'
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'
'------------------------------------------------------------------------------
' COMPUTE DENSITY
'------------------------------------------------------------------------------
    'Compute the standardized variate
        Z = (X - Mean) / StdDev
    'Return the normal density
        K_STATS_Normal_Density = PROB_NormalPDF(Z) / StdDev
'
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_Density = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_Cumulative( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the normal cumulative distribution function at X.
'
' WHY THIS EXISTS
'   Normal cumulative probabilities are used throughout market risk, option
'   pricing, confidence intervals and Gaussian risk-factor modelling.
'
' INPUTS
'   X
'     Evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite X, Mean and StdDev.
'   - Validates positive StdDev.
'   - Standardizes X into Z = (X - Mean) / StdDev.
'   - Returns StandardNormalCDF(Z).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_ValidateNormalInputs
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE CUMULATIVE PROBABILITY
'------------------------------------------------------------------------------
    'Compute the standardized variate
        Z = (X - Mean) / StdDev
    'Return the normal cumulative probability
        K_STATS_Normal_Cumulative = PROB_NormalCDF(Z)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_InverseCumulative( _
    ByVal Probability As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse normal cumulative distribution function.
'
' WHY THIS EXISTS
'   This function maps a probability into a quantile for a normal distribution
'   with user-specified mean and standard deviation.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double normal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates Probability, Mean and StdDev.
'   - Computes Z = StandardNormalInverseCDF(Probability).
'   - Returns Mean + StdDev * Z.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_IsValidProbabilityOpen
'   - PROB_NormalInvCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standard normal quantile
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
    'Validate distribution parameters
        If Not PROB_IsFinite(Mean) Then
            FailMsg = "Mean must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE QUANTILE
'------------------------------------------------------------------------------
    'Compute the standard normal quantile
        Z = PROB_NormalInvCDF(Probability)
    'Return the normal quantile
        K_STATS_Normal_InverseCumulative = Mean + StdDev * Z
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_ZScore( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_ZScore
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standardized normal score Z = (X - Mean) / StdDev.
'
' WHY THIS EXISTS
'   Standardization is frequently shown explicitly in teaching worksheets and
'   model-audit examples before applying the standard normal distribution.
'
' INPUTS
'   X
'     Observation or evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'
' RETURNS
'   Variant
'     Success => Double z-score.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return z-score
        K_STATS_Normal_ZScore = (X - Mean) / StdDev
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_ZScore = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_ZScore: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_ZScore = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_InverseCumulativeFast( _
    ByVal Probability As Double) _
    As Double
'
'==============================================================================
' K_STATS_Normal_InverseCumulativeFast
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function using a
'   fast Double-to-Double contract.
'
' WHY THIS EXISTS
'   Monte Carlo engines transform large volumes of uniform random numbers into
'   standard-normal shocks. This routine avoids the overhead of a worksheet-
'   facing Variant/CVErr interface.
'
' INPUTS
'   Probability
'     Probability level.
'     Expected to be strictly between 0 and 1.
'
' RETURNS
'   Double
'     Standard-normal quantile.
'
' BEHAVIOR
'   - Clips Probability away from 0 and 1 as a defensive safeguard.
'   - Calls the private inverse-normal numerical kernel.
'   - Does not write to the Excel status bar.
'   - Does not return CVErr.
'
' ERROR POLICY
'   - Intended for validated numerical callers.
'   - Endpoint values are clipped rather than rejected.
'   - Public worksheet-facing validation remains the responsibility of
'     K_STATS_Normal_InverseCumulative or K_STATS_NormalStandard_InverseCumulative.
'
' DEPENDENCIES
'   - PROB_NormalInvCDF
'   - PROB_EPS
'
' CALLED FROM
'   - Monte Carlo engines
'   - VBA numerical routines
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' NORMALIZE PROBABILITY
'------------------------------------------------------------------------------
    'Clip probability away from singular endpoints
        If Probability <= 0# Then Probability = PROB_EPS
        If Probability >= 1# Then Probability = 1# - PROB_EPS
'------------------------------------------------------------------------------
' RETURN RESULT
'------------------------------------------------------------------------------
    'Return the inverse standard-normal quantile
        K_STATS_Normal_InverseCumulativeFast = PROB_NormalInvCDF(Probability)
End Function


Public Function K_STATS_Lognormal_Density( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the lognormal probability density function at X.
'
' WHY THIS EXISTS
'   Lognormal distributions are used to model strictly positive variables such
'   as equity prices under geometric Brownian motion and other positive market
'   or economic quantities.
'
' INPUTS
'   X
'     Evaluation point.
'     Must be strictly positive.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates X, MeanLog and StdDevLog.
'   - Computes Z = (Log(X) - MeanLog) / StdDevLog.
'   - Returns StandardNormalDensity(Z) / (X * StdDevLog).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_ValidateLognormalInputs
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized log variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal distribution inputs
        If Not PROB_ValidateLognormalInputs(X, MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE DENSITY
'------------------------------------------------------------------------------
    'Compute standardized log variate
        Z = (Log(X) - MeanLog) / StdDevLog
    'Return lognormal density
        K_STATS_Lognormal_Density = PROB_NormalPDF(Z) / (X * StdDevLog)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Density = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Cumulative( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the lognormal cumulative distribution function at X.
'
' WHY THIS EXISTS
'   Lognormal cumulative probabilities are used for positive market variables,
'   GBM terminal-value examples and probability calculations for positive risk
'   factors.
'
' INPUTS
'   X
'     Evaluation point.
'     For X <= 0, the cumulative probability is 0.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates MeanLog and StdDevLog.
'   - Returns 0 when X <= 0.
'   - Otherwise computes NormalCDF((Log(X) - MeanLog) / StdDevLog).
'
' ERROR POLICY
'   - Invalid parameters return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized log variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE PARAMETERS
'------------------------------------------------------------------------------
    'Validate X is finite
        If Not PROB_IsFinite(X) Then
            FailMsg = "X must be a finite number"
            GoTo Fail_Num
        End If
    'Validate lognormal parameters
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE CUMULATIVE PROBABILITY
'------------------------------------------------------------------------------
    'Return zero for non-positive evaluation points
        If X <= 0# Then
            K_STATS_Lognormal_Cumulative = 0#
            PROB_SetStatus Status, vbNullString
            Exit Function
        End If
    'Compute standardized log variate
        Z = (Log(X) - MeanLog) / StdDevLog
    'Return lognormal cumulative probability
        K_STATS_Lognormal_Cumulative = PROB_NormalCDF(Z)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_InverseCumulative( _
    ByVal Probability As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse lognormal cumulative distribution function.
'
' WHY THIS EXISTS
'   The inverse lognormal distribution maps probabilities into positive quantiles
'   for variables whose logarithm is normally distributed.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
' RETURNS
'   Variant
'     Success => Double positive lognormal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates probability and lognormal parameters.
'   - Computes Z = StandardNormalInverseCDF(Probability).
'   - Returns Exp(MeanLog + StdDevLog * Z).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' DEPENDENCIES
'   - PROB_NormalInvCDF
'   - PROB_SafeExp
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standard normal quantile
    Dim LogQuantile         As Double          'Lognormal log-quantile
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
    'Validate log-space parameters
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE QUANTILE
'------------------------------------------------------------------------------
    'Compute standard normal quantile
        Z = PROB_NormalInvCDF(Probability)
    'Compute log-quantile
        LogQuantile = MeanLog + StdDevLog * Z
    'Return lognormal quantile with safe exponential guard
        K_STATS_Lognormal_InverseCumulative = PROB_SafeExp(LogQuantile)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Mean( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Mean
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the arithmetic mean of a lognormal distribution.
'
' INPUTS
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'
' RETURNS
'   Variant
'     Success => Exp(MeanLog + 0.5 * StdDevLog^2).
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return lognormal mean
        K_STATS_Lognormal_Mean = PROB_SafeExp(MeanLog + 0.5 * StdDevLog * StdDevLog)
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Mean = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Mean: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Mean = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Variance( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Variance
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the arithmetic variance of a lognormal distribution.
'
' INPUTS
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'
' RETURNS
'   Variant
'     Success => (Exp(StdDevLog^2) - 1) * Exp(2 * MeanLog + StdDevLog^2).
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim VarianceLog         As Double          'Variance of Log(X)
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE VARIANCE
'------------------------------------------------------------------------------
    'Compute log variance
        VarianceLog = StdDevLog * StdDevLog
    'Return lognormal variance
        K_STATS_Lognormal_Variance = _
            (PROB_SafeExp(VarianceLog) - 1#) * _
            PROB_SafeExp(2# * MeanLog + VarianceLog)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Variance = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Variance: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Variance = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_ParametersFromMeanStdDev( _
    ByVal Mean As Double, _
    ByVal StdDev As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_ParametersFromMeanStdDev
'------------------------------------------------------------------------------
' PURPOSE
'   Converts arithmetic lognormal mean and standard deviation into log-space
'   parameters.
'
' WHY THIS EXISTS
'   Market and risk inputs are often expressed as arithmetic mean and standard
'   deviation of X, while the lognormal density requires MeanLog and StdDevLog
'   for Log(X).
'
' INPUTS
'   Mean
'     Arithmetic mean of X.
'     Must be strictly positive.
'
'   StdDev
'     Arithmetic standard deviation of X.
'     Must be non-negative.
'
' RETURNS
'   Variant
'     Success => 1 x 2 Variant array:
'                  [1,1] = MeanLog
'                  [1,2] = StdDevLog
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates positive Mean and non-negative StdDev.
'   - Computes:
'       StdDevLog = Sqr(Log(1 + StdDev^2 / Mean^2))
'       MeanLog   = Log(Mean) - 0.5 * StdDevLog^2
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status and Application.StatusBar.
'
' UPDATED
'   2026-07-06
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Result(1 To 1, 1 To 2) As Double       'Output parameter row
    Dim VarianceRatio          As Double       'StdDev^2 / Mean^2
    Dim VarianceLog            As Double       'Variance of Log(X)
    Dim FailMsg                As String       'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate arithmetic mean
        If Not PROB_IsFinite(Mean) Or Mean <= 0# Then
            FailMsg = "Mean must be a finite strictly positive number"
            GoTo Fail_Num
        End If
    'Validate arithmetic standard deviation
        If Not PROB_IsFinite(StdDev) Or StdDev < 0# Then
            FailMsg = "StdDev must be a finite non-negative number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE LOGNORMAL PARAMETERS
'------------------------------------------------------------------------------
    'Compute variance ratio
        VarianceRatio = (StdDev * StdDev) / (Mean * Mean)
    'Compute log variance
        VarianceLog = Log(1# + VarianceRatio)
    'Populate output parameters
        Result(1, 2) = Sqr(VarianceLog)
        Result(1, 1) = Log(Mean) - 0.5 * VarianceLog
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return 1 x 2 parameter row
        K_STATS_Lognormal_ParametersFromMeanStdDev = Result
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_ParametersFromMeanStdDev = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_ParametersFromMeanStdDev: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_ParametersFromMeanStdDev = CVErr(xlErrValue)
End Function


'==============================================================================
' PRIVATE NUMERICAL KERNELS
'==============================================================================

Private Function PROB_NormalPDF( _
    ByVal Z As Double) _
    As Double
'
'==============================================================================
' PROB_NormalPDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal density using a fast Double-to-Double contract.
'==============================================================================
'
'------------------------------------------------------------------------------
' COMPUTE
'------------------------------------------------------------------------------
    'Protect against numerical underflow in the extreme tails
        If Abs(Z) > 38# Then
            PROB_NormalPDF = 0#
        Else
            PROB_NormalPDF = PROB_INV_SQRT_TWO_PI * Exp(-0.5 * Z * Z)
        End If
End Function


Private Function PROB_NormalCDF( _
    ByVal Z As Double) _
    As Double
'
'==============================================================================
' PROB_NormalCDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal cumulative distribution function.
'
' METHOD
'   Double-precision rational approximation based on Hart-style coefficients.
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Y                   As Double          'Absolute z value
    Dim Exponential         As Double          'Exp(-0.5 * Y^2)
    Dim SumA                As Double          'Numerator accumulator
    Dim SumB                As Double          'Denominator accumulator
    Dim TailProbability     As Double          'Lower-tail probability for |Z|
'------------------------------------------------------------------------------
' COMPUTE
'------------------------------------------------------------------------------
    'Work with absolute value
        Y = Abs(Z)
    'Handle extreme tails directly
        If Y > 37# Then
            If Z > 0# Then
                PROB_NormalCDF = 1#
            Else
                PROB_NormalCDF = 0#
            End If

            Exit Function
        End If
    'Compute exponential term
        Exponential = Exp(-0.5 * Y * Y)
    'Use rational approximation in main region
        If Y < 7.07106781186547 Then
            SumA = 3.52624965998911E-02 * Y + 0.700383064443688
            SumA = SumA * Y + 6.37396220353165
            SumA = SumA * Y + 33.912866078383
            SumA = SumA * Y + 112.079291497871
            SumA = SumA * Y + 221.213596169931
            SumA = SumA * Y + 220.206867912376

            SumB = 8.83883476483184E-02 * Y + 1.75566716318264
            SumB = SumB * Y + 16.064177579207
            SumB = SumB * Y + 86.7807322029461
            SumB = SumB * Y + 296.564248779674
            SumB = SumB * Y + 637.333633378831
            SumB = SumB * Y + 793.826512519948
            SumB = SumB * Y + 440.413735824752

            TailProbability = Exponential * SumA / SumB
    'Use continued-fraction approximation in far tail
        Else
            SumA = Y + 0.65
            SumA = Y + 4# / SumA
            SumA = Y + 3# / SumA
            SumA = Y + 2# / SumA
            SumA = Y + 1# / SumA

            TailProbability = Exponential / (SumA * PROB_SQRT_TWO_PI)
        End If
    'Reflect according to the sign of Z
        If Z > 0# Then
            PROB_NormalCDF = 1# - TailProbability
        Else
            PROB_NormalCDF = TailProbability
        End If
End Function


Private Function PROB_NormalInvCDF( _
    ByVal Probability As Double) _
    As Double
'
'==============================================================================
' PROB_NormalInvCDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function.
'
' METHOD
'   Peter J. Acklam's rational approximation.
'
' PRECONDITION
'   Probability must be strictly between 0 and 1.
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE CONSTANTS
'------------------------------------------------------------------------------
    Const A1 As Double = -39.6968302866538
    Const A2 As Double = 220.946098424521
    Const A3 As Double = -275.928510446969
    Const A4 As Double = 138.357751867269
    Const A5 As Double = -30.6647980661472
    Const A6 As Double = 2.50662827745924

    Const B1 As Double = -54.4760987982241
    Const B2 As Double = 161.585836858041
    Const B3 As Double = -155.698979859887
    Const B4 As Double = 66.8013118877197
    Const B5 As Double = -13.2806815528857

    Const C1 As Double = -7.78489400243029E-03
    Const C2 As Double = -0.322396458041136
    Const C3 As Double = -2.40075827716184
    Const C4 As Double = -2.54973253934373
    Const C5 As Double = 4.37466414146497
    Const C6 As Double = 2.93816398269878

    Const D1 As Double = 7.78469570904146E-03
    Const D2 As Double = 0.32246712907004
    Const D3 As Double = 2.445134137143
    Const D4 As Double = 3.75440866190742

    Const P_LOW As Double = 0.02425
    Const P_HIGH As Double = 0.97575
'------------------------------------------------------------------------------
' DECLARE VARIABLES
'------------------------------------------------------------------------------
    Dim Q                   As Double          'Working quantile variable
    Dim R                   As Double          'Working polynomial variable
'------------------------------------------------------------------------------
' COMPUTE LOWER TAIL
'------------------------------------------------------------------------------
    'Use lower-tail approximation
        If Probability < P_LOW Then
            Q = Sqr(-2# * Log(Probability))

            PROB_NormalInvCDF = _
                (((((C1 * Q + C2) * Q + C3) * Q + C4) * Q + C5) * Q + C6) / _
                ((((D1 * Q + D2) * Q + D3) * Q + D4) * Q + 1#)

            Exit Function
        End If
'------------------------------------------------------------------------------
' COMPUTE CENTRAL REGION
'------------------------------------------------------------------------------
    'Use central approximation
        If Probability <= P_HIGH Then
            Q = Probability - 0.5
            R = Q * Q

            PROB_NormalInvCDF = _
                (((((A1 * R + A2) * R + A3) * R + A4) * R + A5) * R + A6) * Q / _
                (((((B1 * R + B2) * R + B3) * R + B4) * R + B5) * R + 1#)

            Exit Function
        End If
'------------------------------------------------------------------------------
' COMPUTE UPPER TAIL
'------------------------------------------------------------------------------
    'Use upper-tail approximation
        Q = Sqr(-2# * Log(1# - Probability))

        PROB_NormalInvCDF = _
            -(((((C1 * Q + C2) * Q + C3) * Q + C4) * Q + C5) * Q + C6) / _
            ((((D1 * Q + D2) * Q + D3) * Q + D4) * Q + 1#)
End Function


Private Function PROB_SafeExp( _
    ByVal X As Double) _
    As Double
'
'==============================================================================
' PROB_SafeExp
'------------------------------------------------------------------------------
' PURPOSE
'   Returns Exp(X) with simple overflow and underflow guards.
'==============================================================================
'
'------------------------------------------------------------------------------
' COMPUTE
'------------------------------------------------------------------------------
    'Protect against numerical underflow
        If X <= PROB_MIN_EXP Then
            PROB_SafeExp = 0#
    'Protect against numerical overflow
        ElseIf X >= PROB_MAX_EXP Then
            PROB_SafeExp = PROB_LARGE_NUMBER
    'Return regular exponential
        Else
            PROB_SafeExp = Exp(X)
        End If
End Function


'==============================================================================
' PRIVATE VALIDATION HELPERS
'==============================================================================

Private Function PROB_ValidateNormalInputs( _
    ByVal X As Double, _
    ByVal Mean As Double, _
    ByVal StdDev As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateNormalInputs
'------------------------------------------------------------------------------
' PURPOSE
'   Validates inputs for a normal distribution with mean and standard deviation.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate X
        If Not PROB_IsFinite(X) Then
            FailMsg = "X must be a finite number"
            Exit Function
        End If
    'Validate mean
        If Not PROB_IsFinite(Mean) Then
            FailMsg = "Mean must be a finite number"
            Exit Function
        End If
    'Validate standard deviation
        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            Exit Function
        End If
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateNormalInputs = True
End Function


Private Function PROB_ValidateLognormalInputs( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateLognormalInputs
'------------------------------------------------------------------------------
' PURPOSE
'   Validates inputs for lognormal density calculations.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate evaluation point
        If Not PROB_IsFinite(X) Or X <= 0# Then
            FailMsg = "X must be a finite strictly positive number"
            Exit Function
        End If
    'Validate log-space parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then Exit Function
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateLognormalInputs = True
End Function


Private Function PROB_ValidateLogParameters( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateLogParameters
'------------------------------------------------------------------------------
' PURPOSE
'   Validates log-space lognormal parameters.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate log mean
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            Exit Function
        End If
    'Validate log standard deviation
        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            Exit Function
        End If
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateLogParameters = True
End Function


Private Function PROB_IsValidProbabilityOpen( _
    ByVal Probability As Double) _
    As Boolean
'
'==============================================================================
' PROB_IsValidProbabilityOpen
'------------------------------------------------------------------------------
' PURPOSE
'   Returns TRUE when Probability is finite and strictly inside (0, 1).
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Reject non-finite probabilities
        If Not PROB_IsFinite(Probability) Then Exit Function
    'Reject endpoints and values outside the unit interval
        If Probability <= 0# Or Probability >= 1# Then Exit Function
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_IsValidProbabilityOpen = True
End Function


Private Function PROB_IsFinite( _
    ByVal X As Double) _
    As Boolean
'
'==============================================================================
' PROB_IsFinite
'------------------------------------------------------------------------------
' PURPOSE
'   Performs a lightweight finite-number check for VBA Double inputs.
'==============================================================================
'
'------------------------------------------------------------------------------
' RETURN
'------------------------------------------------------------------------------
    'Return TRUE when X is not NaN and is inside a conservative magnitude bound
        PROB_IsFinite = (X = X And Abs(X) < PROB_LARGE_NUMBER)
End Function


Private Sub PROB_SetStatus( _
    ByRef Status As String, _
    ByVal Message As String)
'
'==============================================================================
' PROB_SetStatus
'------------------------------------------------------------------------------
' PURPOSE
'   Writes a diagnostic message to the optional Status argument and to the Excel
'   status bar.
'==============================================================================
'
'------------------------------------------------------------------------------
' UPDATE STATUS
'------------------------------------------------------------------------------
    'Suppress non-critical status-bar side effects
        On Error Resume Next
    'Write the ByRef diagnostic message
        Status = Message
    'Update Excel status bar
        If Len(Message) = 0 Then
            Application.StatusBar = False
        Else
            Application.StatusBar = Message
        End If
End Sub


