Attribute VB_Name = "M_STATS_PROBDIST_NORMALFAMILY"

Option Explicit

'==============================================================================
' M_STATS_PROBDIST_NORMALFAMILY
'------------------------------------------------------------------------------
' PURPOSE
'   Provides robust normal-family probability distribution functions for
'   worksheet formulas, VBA models and Monte Carlo engines.
'
' WHY THIS EXISTS
'   The normal distribution is the core distribution used in Black-Scholes,
'   value-at-risk examples, regression diagnostics, Gaussian copulas and Monte
'   Carlo simulation. The lognormal distribution is the natural companion for
'   positive variables generated by geometric Brownian motion, including equity
'   prices and other strictly positive market factors.
'
'   Native Excel worksheet functions cover most of these distributions
'   (see WORKSHEET EQUIVALENTS below), but they are awkward to call from VBA:
'   Application.WorksheetFunction raises a trappable runtime error on bad input
'   instead of returning CVErr, and carries per-call marshalling overhead. This
'   module gives a single, VBA-native, consistently-validated surface that is
'   equally callable from a cell and from a tight numerical loop, plus helpers
'   that have no native equivalent at all.
'
' PUBLIC FUNCTIONS
'   Standard normal:
'     - K_STATS_NormalStandard_Density
'     - K_STATS_NormalStandard_Cumulative
'     - K_STATS_NormalStandard_InverseCumulative
'     - K_STATS_NormalStandard_IntervalProbability
'     - K_STATS_NormalStandard_InverseCumulativeFast
'
'   General normal:
'     - K_STATS_Normal_Density
'     - K_STATS_Normal_Cumulative
'     - K_STATS_Normal_InverseCumulative
'     - K_STATS_Normal_ZScore
'     - K_STATS_Normal_IntervalProbability
'
'   Lognormal:
'     - K_STATS_Lognormal_Density
'     - K_STATS_Lognormal_Cumulative
'     - K_STATS_Lognormal_InverseCumulative
'     - K_STATS_Lognormal_Mean
'     - K_STATS_Lognormal_Variance
'     - K_STATS_Lognormal_StdDev
'     - K_STATS_Lognormal_ParametersFromMeanStdDev
'
' WORKSHEET EQUIVALENTS (native Excel, 2010+ unless noted)
'   K_STATS_NormalStandard_Density              NORM.S.DIST(z, FALSE)
'   K_STATS_NormalStandard_Cumulative           NORM.S.DIST(z, TRUE)   [legacy NORMSDIST]
'   K_STATS_NormalStandard_InverseCumulative    NORM.S.INV(p)          [legacy NORMSINV]
'   K_STATS_NormalStandard_IntervalProbability  NORM.S.DIST(b,TRUE) - NORM.S.DIST(a,TRUE)
'   K_STATS_NormalStandard_InverseCumulativeFast (none - numeric helper)
'   K_STATS_Normal_Density                      NORM.DIST(x, m, s, FALSE)
'   K_STATS_Normal_Cumulative                   NORM.DIST(x, m, s, TRUE)
'   K_STATS_Normal_InverseCumulative            NORM.INV(p, m, s)
'   K_STATS_Normal_ZScore                       STANDARDIZE(x, m, s)
'   K_STATS_Normal_IntervalProbability          NORM.DIST(b,m,s,TRUE) - NORM.DIST(a,m,s,TRUE)
'   K_STATS_Lognormal_Density                   LOGNORM.DIST(x, m, s, FALSE)
'   K_STATS_Lognormal_Cumulative                LOGNORM.DIST(x, m, s, TRUE) [legacy LOGNORMDIST, cumulative only]
'   K_STATS_Lognormal_InverseCumulative         LOGNORM.INV(p, m, s)        [legacy LOGINV]
'   K_STATS_Lognormal_Mean                      (none - use EXP(m + 0.5*s^2))
'   K_STATS_Lognormal_Variance                  (none)
'   K_STATS_Lognormal_StdDev                    (none - SQRT of lognormal variance)
'   K_STATS_Lognormal_ParametersFromMeanStdDev  (none - custom method-of-moments)
'
' ALGORITHM PROVENANCE
'   - Standard normal CDF (PROB_NormalCDF):
'       Hart rational/continued-fraction approximation (Hart et al.,
'       "Computer Approximations", 1968), in the double-precision arrangement
'       popularised by Graeme West, "Better Approximations to Cumulative Normal
'       Functions" (Wilmott Magazine, 2009). Public, published; not proprietary.
'       Accurate to approximately 1E-15.
'   - Inverse standard normal (PROB_NormalInvCDF):
'       Peter J. Acklam's rational approximation (released freely for any use by
'       the author), taken from the shared kernel PROB_NormalInvCDFRaw in
'       M_STATS_CORE and refined here with a single Halley iteration. Raw Acklam
'       alone is accurate to ~1.15E-9 relative; the Halley step lifts the central
'       region to ~5E-16. In the tail the Halley step is bounded by the RELATIVE
'       accuracy of PROB_NormalCDF (about 1E-10 past z = 7.07), and beyond
'       z = 37 it is skipped entirely because the CDF has saturated. Public.
'   - Lognormal moment and parameter formulas:
'       Standard closed-form textbook results (method of moments). Not proprietary.
'   The raw Acklam kernel lives in M_STATS_CORE as PROB_NormalInvCDFRaw, because
'   the Student t quantile seeds off it too. Only the Halley refinement, which is
'   normal-family-specific, remains here.
'   Nothing in this module is a newly-invented algorithm; the design/packaging,
'   validation policy and the fast Double contract are the local contribution.
'
' DESIGN PRINCIPLES
'   - Public worksheet-facing functions return Variant so they can return CVErr.
'   - Private numerical kernels return Double and avoid worksheet-facing overhead.
'   - The fast inverse-normal routine is exposed for Monte Carlo engines and
'     deliberately uses the raw (unrefined) Acklam kernel for speed.
'   - Invalid domains fail explicitly; they are not silently repaired.
'   - Overflow fails explicitly: a computation that would exceed Double range
'     returns CVErr(xlErrNum) rather than a clamped sentinel value.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Overflow of an exponential result returns CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status; the Excel status bar
'     is updated only when PROB_WRITE_STATUS_BAR is True (default False).
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - M_STATS_CORE
'       Constants  : PROB_EPS, PROB_DOUBLE_MAX, PROB_MAX_EXP, PROB_MIN_EXP,
'                    PROB_LARGE_NUMBER, PROB_WRITE_STATUS_BAR
'       Predicates : PROB_IsFinite, PROB_IsValidProbabilityOpen
'       Primitives : PROB_TryExp, PROB_NormalInvCDFRaw
'       Diagnostics: PROB_SetStatus
'
' NOTES
'   - Lognormal parameters are the mean and standard deviation of Log(X), not of X.
'   - K_STATS_Lognormal_ParametersFromMeanStdDev converts arithmetic mean and standard
'     deviation into log-space parameters; both inputs must be strictly positive.
'   - K_STATS_NormalStandard_InverseCumulativeFast intentionally clips probabilities at
'     the endpoints and returns Double; use it only for validated numerical callers.
'   - Overflow policy: PROB_TryExp fails (returns False) when Exp would overflow a
'     Double. The lognormal Mean, Variance, StdDev and InverseCumulative routines
'     translate that into CVErr(xlErrNum). Underflow of an exponential is a valid
'     zero, not an error.
'   - Status-bar writes: gated behind PROB_WRITE_STATUS_BAR (default False).
'     Status-bar writes from a worksheet UDF are unreliable and add churn when a
'     function is bulk-filled; the ByRef Status argument is always populated and
'     is the intended diagnostic channel.
'   - VBA's And and Or are not short-circuit: both operands are always evaluated.
'     Any guard whose right operand can fault (a division, a Log of a non-positive
'     number) must be nested, never And-ed. See K_STATS_Lognormal_Variance and
'     K_STATS_Lognormal_StdDev.
'
' UPDATED
'   2026-07-09
'==============================================================================

'==============================================================================
' PRIVATE CONSTANTS
'==============================================================================

' Shared constants (PROB_EPS, PROB_MAX_EXP, PROB_MIN_EXP, PROB_LARGE_NUMBER,
' PROB_DOUBLE_MAX, PROB_WRITE_STATUS_BAR) now live in M_STATS_CORE. Only the
' normal-family-specific constants remain here. PROB_PI and PROB_TWO_PI were
' declared but never referenced and have been dropped.

Private Const PROB_SQRT_TWO_PI         As Double = 2.506628274631       'Sqr(2 * Pi), correctly rounded
Private Const PROB_INV_SQRT_TWO_PI     As Double = 0.398942280401433    '1 / Sqr(2 * Pi), correctly rounded
Private Const PROB_PDF_TAIL_CUTOFF     As Double = 38#               'Abs(Z) beyond which the density underflows to 0
Private Const PROB_CDF_TAIL_CUTOFF     As Double = 37#               'Abs(Z) beyond which the CDF saturates to 0/1
Private Const PROB_CDF_SPLIT           As Double = 7.07106781186547  'Sqr(50): rational vs continued-fraction split





Public Function K_STATS_NormalStandard_Density( _
    ByVal Z As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal probability density function at Z.
'
' WHY THIS EXISTS
'   The standard normal density is used in option Greeks, likelihood examples,
'   regression diagnostics and probability-distribution teaching worksheets.
'
' WORKSHEET EQUIVALENT
'   NORM.S.DIST(Z, FALSE)  (Excel 2010+). This VBA form is CVErr-clean and
'   directly callable from numerical code.
'
' PROVENANCE
'   Closed-form standard normal density. Not proprietary.
'
' INPUTS
'   Z
'     Standard-normal variate.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates that Z is finite.
'   - Returns Exp(-0.5 * Z^2) / Sqr(2 * Pi).
'
' ERROR POLICY
'   - Non-finite inputs return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' CALLED FROM
'   - Excel worksheet formulas
'   - VBA callers
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message

'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString

'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite input
        If Not PROB_IsFinite(Z) Then
            FailMsg = "Z must be a finite number"
            GoTo Fail_Num
        End If

'------------------------------------------------------------------------------
' COMPUTE DENSITY
'------------------------------------------------------------------------------
    'Return standard normal density
        K_STATS_NormalStandard_Density = PROB_NormalPDF(Z)

'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function

'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function

'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_Density = CVErr(xlErrValue)

End Function


Public Function K_STATS_NormalStandard_Cumulative( _
    ByVal Z As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal cumulative distribution function at Z.
'
' WHY THIS EXISTS
'   The standard normal cumulative distribution is a core building block for
'   Black-Scholes formulas, Gaussian risk-factor models and probability examples.
'
' WORKSHEET EQUIVALENT
'   NORM.S.DIST(Z, TRUE)  (Excel 2010+); legacy NORMSDIST(Z).
'
' PROVENANCE
'   Hart rational/continued-fraction approximation (Hart 1968) in the
'   double-precision arrangement popularised by Graeme West (Wilmott, 2009).
'   Public; accurate to ~1E-15.
'
' INPUTS
'   Z
'     Standard-normal variate.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates that Z is finite.
'   - Computes the cumulative probability using a double-precision rational
'     approximation.
'
' ERROR POLICY
'   - Non-finite inputs return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'

'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message

'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString

'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite input
        If Not PROB_IsFinite(Z) Then
            FailMsg = "Z must be a finite number"
            GoTo Fail_Num
        End If

'------------------------------------------------------------------------------
' COMPUTE CUMULATIVE PROBABILITY
'------------------------------------------------------------------------------
    'Return standard normal cumulative probability
        K_STATS_NormalStandard_Cumulative = PROB_NormalCDF(Z)

'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function

'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function

'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_NormalStandard_InverseCumulative( _
    ByVal Probability As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function.
'
' WHY THIS EXISTS
'   The inverse standard normal is used to convert probabilities into normal
'   quantiles, for example in VaR, scenario generation and Monte Carlo shocks.
'
' WORKSHEET EQUIVALENT
'   NORM.S.INV(Probability)  (Excel 2010+); legacy NORMSINV(Probability).
'
' PROVENANCE
'   Peter J. Acklam's rational approximation (public, released freely) with a
'   single Halley refinement step. Accurate to ~1E-15.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   Status
'     Optional ByRef diagnostic message.
'     Empty on success.
'     Populated on failure.
'
' RETURNS
'   Variant
'     Success => Double standard-normal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates that Probability is finite and strictly inside (0, 1).
'   - Uses Acklam's rational approximation refined by one Halley iteration.
'
' ERROR POLICY
'   - Invalid probabilities return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'   - No MsgBox is raised.
'
' DEPENDENCIES
'   - PROB_IsValidProbabilityOpen
'   - PROB_NormalInvCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message
'
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
'
'------------------------------------------------------------------------------
' COMPUTE QUANTILE
'------------------------------------------------------------------------------
    'Return inverse standard normal cumulative probability
        K_STATS_NormalStandard_InverseCumulative = PROB_NormalInvCDF(Probability)
'
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_NormalStandard_IntervalProbability( _
    ByVal LowerZ As Double, _
    ByVal UpperZ As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_NormalStandard_IntervalProbability
'------------------------------------------------------------------------------
' PURPOSE
'   Returns P(LowerZ <= Z <= UpperZ) for the standard normal distribution.
'
' WHY THIS EXISTS
'   Interval (band) probabilities are used for confidence-region masses,
'   two-sided tail budgeting and probability-of-touching style calculations.
'
' WORKSHEET EQUIVALENT
'   NORM.S.DIST(UpperZ, TRUE) - NORM.S.DIST(LowerZ, TRUE).
'
' PROVENANCE
'   Difference of standard normal CDFs (Hart/West). Not proprietary.
'
' INPUTS
'   LowerZ
'     Lower standard-normal bound.
'
'   UpperZ
'     Upper standard-normal bound.
'     Must be greater than or equal to LowerZ.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double interval probability in [0, 1].
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite bounds and UpperZ >= LowerZ.
'   - Returns NormalCDF(UpperZ) - NormalCDF(LowerZ).
'   - Clamps a tiny negative rounding residual to 0.
'
' ERROR POLICY
'   - Invalid or reversed bounds return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Probability         As Double          'Interval probability
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite bounds
        If Not PROB_IsFinite(LowerZ) Then
            FailMsg = "LowerZ must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(UpperZ) Then
            FailMsg = "UpperZ must be a finite number"
            GoTo Fail_Num
        End If
    'Validate ordering
        If UpperZ < LowerZ Then
            FailMsg = "UpperZ must be greater than or equal to LowerZ"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE INTERVAL PROBABILITY
'------------------------------------------------------------------------------
    'Difference of cumulative probabilities
        Probability = PROB_NormalCDF(UpperZ) - PROB_NormalCDF(LowerZ)
    'Clamp tiny negative rounding residual
        If Probability < 0# Then Probability = 0#
    'Return interval probability
        K_STATS_NormalStandard_IntervalProbability = Probability
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_NormalStandard_IntervalProbability = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_NormalStandard_IntervalProbability: " & Err.Description
    'Return worksheet value error
        K_STATS_NormalStandard_IntervalProbability = CVErr(xlErrValue)
End Function


Public Function K_STATS_NormalStandard_InverseCumulativeFast( _
    ByVal Probability As Double) _
    As Double
'
'==============================================================================
' K_STATS_NormalStandard_InverseCumulativeFast
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function using a
'   fast Double-to-Double contract.
'
' WHY THIS EXISTS
'   Monte Carlo engines transform large volumes of uniform random numbers into
'   standard-normal shocks. This routine avoids the overhead of a worksheet-
'   facing Variant/CVErr interface.
'
' WORKSHEET EQUIVALENT
'   None. This is a numerical helper, not a worksheet function.
'
' PROVENANCE
'   Raw Peter J. Acklam rational approximation (public), via the shared kernel
'   PROB_NormalInvCDFRaw in M_STATS_CORE. The Halley refinement
'   used by the worksheet-facing inverse is deliberately NOT applied here: for
'   Monte Carlo the ~1.15E-9 relative error is far below sampling error and the
'   unrefined kernel is materially faster.
'
' INPUTS
'   Probability
'     Probability level.
'     Expected to be strictly between 0 and 1.
'
' RETURNS
'   Double
'     Standard-normal quantile.
'
' BEHAVIOR
'   - Clips Probability away from 0 and 1 as a defensive safeguard.
'   - Calls the raw (unrefined) inverse-normal numerical kernel.
'   - Does not write to the Excel status bar.
'   - Does not return CVErr.
'
' ERROR POLICY
'   - Intended for validated numerical callers.
'   - Endpoint values are clipped rather than rejected.
'   - Public worksheet-facing validation remains the responsibility of
'     K_STATS_Normal_InverseCumulative or K_STATS_NormalStandard_InverseCumulative.
'
' DEPENDENCIES
'   - PROB_NormalInvCDFRaw   (M_STATS_CORE)
'   - PROB_EPS               (M_STATS_CORE)
'
' CALLED FROM
'   - Monte Carlo engines
'   - VBA numerical routines
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' NORMALIZE PROBABILITY
'------------------------------------------------------------------------------
    'Clip probability away from singular endpoints
        If Probability <= 0# Then Probability = PROB_EPS
        If Probability >= 1# Then Probability = 1# - PROB_EPS
'------------------------------------------------------------------------------
' RETURN RESULT
'------------------------------------------------------------------------------
    'Return the raw inverse standard-normal quantile
        K_STATS_NormalStandard_InverseCumulativeFast = PROB_NormalInvCDFRaw(Probability)
End Function


Public Function K_STATS_Normal_Density( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the normal probability density function at X.
'
' WHY THIS EXISTS
'   Many risk, pricing and statistical models require normal densities with a
'   configurable mean and standard deviation, not only the standard normal case.
'
' WORKSHEET EQUIVALENT
'   NORM.DIST(X, Mean, StdDev, FALSE)  (Excel 2010+).
'
' PROVENANCE
'   Closed-form normal density via standardization. Not proprietary.
'
' INPUTS
'   X
'     Evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite X, Mean and StdDev.
'   - Validates positive StdDev.
'   - Standardizes X into Z = (X - Mean) / StdDev.
'   - Returns StandardNormalDensity(Z) / StdDev.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_ValidateNormalInputs
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized variate
    Dim FailMsg             As String          'Detailed failure message
'
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'
'------------------------------------------------------------------------------
' COMPUTE DENSITY
'------------------------------------------------------------------------------
    'Compute the standardized variate
        Z = (X - Mean) / StdDev
    'Return the normal density
        K_STATS_Normal_Density = PROB_NormalPDF(Z) / StdDev
'
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_Density = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_Cumulative( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the normal cumulative distribution function at X.
'
' WHY THIS EXISTS
'   Normal cumulative probabilities are used throughout market risk, option
'   pricing, confidence intervals and Gaussian risk-factor modelling.
'
' WORKSHEET EQUIVALENT
'   NORM.DIST(X, Mean, StdDev, TRUE)  (Excel 2010+).
'
' PROVENANCE
'   Hart/West standard normal CDF via standardization. Public; ~1E-15 accurate.
'
' INPUTS
'   X
'     Evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite X, Mean and StdDev.
'   - Validates positive StdDev.
'   - Standardizes X into Z = (X - Mean) / StdDev.
'   - Returns StandardNormalCDF(Z).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_ValidateNormalInputs
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE CUMULATIVE PROBABILITY
'------------------------------------------------------------------------------
    'Compute the standardized variate
        Z = (X - Mean) / StdDev
    'Return the normal cumulative probability
        K_STATS_Normal_Cumulative = PROB_NormalCDF(Z)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_InverseCumulative( _
    ByVal Probability As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse normal cumulative distribution function.
'
' WHY THIS EXISTS
'   This function maps a probability into a quantile for a normal distribution
'   with user-specified mean and standard deviation.
'
' WORKSHEET EQUIVALENT
'   NORM.INV(Probability, Mean, StdDev)  (Excel 2010+).
'
' PROVENANCE
'   Acklam inverse (Halley-refined) rescaled to Mean/StdDev. Public; ~1E-15.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double normal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates Probability, Mean and StdDev.
'   - Computes Z = StandardNormalInverseCDF(Probability).
'   - Returns Mean + StdDev * Z.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsValidProbabilityOpen
'   - PROB_IsFinite
'   - PROB_NormalInvCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standard normal quantile
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
    'Validate distribution parameters
        If Not PROB_IsFinite(Mean) Then
            FailMsg = "Mean must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE QUANTILE
'------------------------------------------------------------------------------
    'Compute the standard normal quantile
        Z = PROB_NormalInvCDF(Probability)
    'Return the normal quantile
        K_STATS_Normal_InverseCumulative = Mean + StdDev * Z
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_ZScore( _
    ByVal X As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_ZScore
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standardized normal score Z = (X - Mean) / StdDev.
'
' WHY THIS EXISTS
'   Standardization is frequently shown explicitly in teaching worksheets and
'   model-audit examples before applying the standard normal distribution.
'
' WORKSHEET EQUIVALENT
'   STANDARDIZE(X, Mean, StdDev).
'
' PROVENANCE
'   Trivial closed-form standardization. Not proprietary.
'
' INPUTS
'   X
'     Observation or evaluation point.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'
' RETURNS
'   Variant
'     Success => Double z-score.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate normal distribution inputs
        If Not PROB_ValidateNormalInputs(X, Mean, StdDev, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE Z-SCORE
'------------------------------------------------------------------------------
    'Return z-score
        K_STATS_Normal_ZScore = (X - Mean) / StdDev
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_ZScore = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_ZScore: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_ZScore = CVErr(xlErrValue)
End Function


Public Function K_STATS_Normal_IntervalProbability( _
    ByVal LowerBound As Double, _
    ByVal UpperBound As Double, _
    Optional ByVal Mean As Double = 0#, _
    Optional ByVal StdDev As Double = 1#, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Normal_IntervalProbability
'------------------------------------------------------------------------------
' PURPOSE
'   Returns P(LowerBound <= X <= UpperBound) for a normal distribution with the
'   given mean and standard deviation.
'
' WHY THIS EXISTS
'   Band probabilities on a general normal are used for tolerance masses,
'   confidence-interval coverage and probability-in-range calculations.
'
' WORKSHEET EQUIVALENT
'   NORM.DIST(UpperBound, Mean, StdDev, TRUE) - NORM.DIST(LowerBound, Mean, StdDev, TRUE).
'
' PROVENANCE
'   Difference of normal CDFs (Hart/West) via standardization. Not proprietary.
'
' INPUTS
'   LowerBound
'     Lower evaluation bound.
'
'   UpperBound
'     Upper evaluation bound.
'     Must be greater than or equal to LowerBound.
'
'   Mean
'     Distribution mean.
'
'   StdDev
'     Distribution standard deviation.
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double interval probability in [0, 1].
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates finite bounds, finite Mean and positive StdDev.
'   - Validates UpperBound >= LowerBound.
'   - Standardizes both bounds and returns NormalCDF(zU) - NormalCDF(zL).
'   - Clamps a tiny negative rounding residual to 0.
'
' ERROR POLICY
'   - Invalid or reversed bounds return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim ZLower              As Double          'Standardized lower bound
    Dim ZUpper              As Double          'Standardized upper bound
    Dim Probability         As Double          'Interval probability
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate finite bounds
        If Not PROB_IsFinite(LowerBound) Then
            FailMsg = "LowerBound must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(UpperBound) Then
            FailMsg = "UpperBound must be a finite number"
            GoTo Fail_Num
        End If
    'Validate distribution parameters
        If Not PROB_IsFinite(Mean) Then
            FailMsg = "Mean must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            GoTo Fail_Num
        End If
    'Validate ordering
        If UpperBound < LowerBound Then
            FailMsg = "UpperBound must be greater than or equal to LowerBound"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE INTERVAL PROBABILITY
'------------------------------------------------------------------------------
    'Standardize both bounds
        ZLower = (LowerBound - Mean) / StdDev
        ZUpper = (UpperBound - Mean) / StdDev
    'Difference of cumulative probabilities
        Probability = PROB_NormalCDF(ZUpper) - PROB_NormalCDF(ZLower)
    'Clamp tiny negative rounding residual
        If Probability < 0# Then Probability = 0#
    'Return interval probability
        K_STATS_Normal_IntervalProbability = Probability
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Normal_IntervalProbability = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Normal_IntervalProbability: " & Err.Description
    'Return worksheet value error
        K_STATS_Normal_IntervalProbability = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Density( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Density
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the lognormal probability density function at X.
'
' WHY THIS EXISTS
'   Lognormal distributions are used to model strictly positive variables such
'   as equity prices under geometric Brownian motion and other positive market
'   or economic quantities.
'
' WORKSHEET EQUIVALENT
'   LOGNORM.DIST(X, MeanLog, StdDevLog, FALSE)  (Excel 2010+).
'
' PROVENANCE
'   Closed-form lognormal density built on the standard normal density.
'   Not proprietary.
'
' INPUTS
'   X
'     Evaluation point.
'     Must be strictly positive.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
'   Status
'     Optional ByRef diagnostic message.
'
' RETURNS
'   Variant
'     Success => Double density value.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates X, MeanLog and StdDevLog.
'   - Computes Z = (Log(X) - MeanLog) / StdDevLog.
'   - Returns StandardNormalDensity(Z) / (X * StdDevLog).
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_ValidateLognormalInputs
'   - PROB_NormalPDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized log variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal distribution inputs
        If Not PROB_ValidateLognormalInputs(X, MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE DENSITY
'------------------------------------------------------------------------------
    'Compute standardized log variate
        Z = (Log(X) - MeanLog) / StdDevLog
    'Return lognormal density
        K_STATS_Lognormal_Density = PROB_NormalPDF(Z) / (X * StdDevLog)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Density = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Density: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Density = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Cumulative( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Cumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the lognormal cumulative distribution function at X.
'
' WHY THIS EXISTS
'   Lognormal cumulative probabilities are used for positive market variables,
'   GBM terminal-value examples and probability calculations for positive risk
'   factors.
'
' WORKSHEET EQUIVALENT
'   LOGNORM.DIST(X, MeanLog, StdDevLog, TRUE)  (Excel 2010+); legacy
'   LOGNORMDIST(X, MeanLog, StdDevLog) (cumulative only). Note the native
'   functions return #NUM! for X <= 0 whereas this routine returns 0, which is
'   the mathematically correct left-tail value for a positive-support variable.
'
' PROVENANCE
'   Standard normal CDF (Hart/West) of the standardized log variate. Public.
'
' INPUTS
'   X
'     Evaluation point.
'     For X <= 0, the cumulative probability is 0.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
' RETURNS
'   Variant
'     Success => Double cumulative probability.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates MeanLog and StdDevLog.
'   - Returns 0 when X <= 0.
'   - Otherwise computes NormalCDF((Log(X) - MeanLog) / StdDevLog).
'
' ERROR POLICY
'   - Invalid parameters return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_NormalCDF
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standardized log variate
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE PARAMETERS
'------------------------------------------------------------------------------
    'Validate X is finite
        If Not PROB_IsFinite(X) Then
            FailMsg = "X must be a finite number"
            GoTo Fail_Num
        End If
    'Validate lognormal parameters
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE CUMULATIVE PROBABILITY
'------------------------------------------------------------------------------
    'Return zero for non-positive evaluation points
        If X <= 0# Then
            K_STATS_Lognormal_Cumulative = 0#
            PROB_SetStatus Status, vbNullString
            Exit Function
        End If
    'Compute standardized log variate
        Z = (Log(X) - MeanLog) / StdDevLog
    'Return lognormal cumulative probability
        K_STATS_Lognormal_Cumulative = PROB_NormalCDF(Z)
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Cumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Cumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Cumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_InverseCumulative( _
    ByVal Probability As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_InverseCumulative
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse lognormal cumulative distribution function.
'
' WHY THIS EXISTS
'   The inverse lognormal distribution maps probabilities into positive quantiles
'   for variables whose logarithm is normally distributed.
'
' WORKSHEET EQUIVALENT
'   LOGNORM.INV(Probability, MeanLog, StdDevLog)  (Excel 2010+); legacy
'   LOGINV(Probability, MeanLog, StdDevLog).
'
' PROVENANCE
'   Acklam inverse (Halley-refined) mapped through Exp(). Public.
'
' INPUTS
'   Probability
'     Probability level.
'     Must be strictly between 0 and 1.
'
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'     Must be strictly positive.
'
' RETURNS
'   Variant
'     Success => Double positive lognormal quantile.
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates probability and lognormal parameters.
'   - Computes Z = StandardNormalInverseCDF(Probability).
'   - Returns Exp(MeanLog + StdDevLog * Z), or CVErr(xlErrNum) on overflow.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Overflow of the exponential returns CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsValidProbabilityOpen
'   - PROB_IsFinite
'   - PROB_NormalInvCDF
'   - PROB_TryExp
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Z                   As Double          'Standard normal quantile
    Dim LogQuantile         As Double          'Lognormal log-quantile
    Dim Quantile            As Double          'Lognormal quantile
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate probability domain
        If Not PROB_IsValidProbabilityOpen(Probability) Then
            FailMsg = "Probability must be strictly between 0 and 1"
            GoTo Fail_Num
        End If
    'Validate log-space parameters
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            GoTo Fail_Num
        End If

        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE QUANTILE
'------------------------------------------------------------------------------
    'Compute standard normal quantile
        Z = PROB_NormalInvCDF(Probability)
    'Compute log-quantile
        LogQuantile = MeanLog + StdDevLog * Z
    'Exponentiate with explicit overflow detection
        If Not PROB_TryExp(LogQuantile, Quantile) Then
            FailMsg = "Lognormal quantile overflows Double range"
            GoTo Fail_Num
        End If
    'Return lognormal quantile
        K_STATS_Lognormal_InverseCumulative = Quantile
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_InverseCumulative = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_InverseCumulative: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_InverseCumulative = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Mean( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Mean
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the arithmetic mean of a lognormal distribution.
'
' WORKSHEET EQUIVALENT
'   None native. Equivalent to EXP(MeanLog + 0.5 * StdDevLog^2).
'
' PROVENANCE
'   Standard closed-form lognormal first moment. Not proprietary.
'
' INPUTS
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'
' RETURNS
'   Variant
'     Success => Exp(MeanLog + 0.5 * StdDevLog^2).
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' ERROR POLICY
'   - Invalid parameters return CVErr(xlErrNum).
'   - Overflow of the exponential returns CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'
' DEPENDENCIES
'   - PROB_ValidateLogParameters
'   - PROB_TryExp
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim MeanValue           As Double          'Arithmetic mean
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE MEAN
'------------------------------------------------------------------------------
    'Exponentiate with explicit overflow detection
        If Not PROB_TryExp(MeanLog + 0.5 * StdDevLog * StdDevLog, MeanValue) Then
            FailMsg = "Lognormal mean overflows Double range"
            GoTo Fail_Num
        End If
    'Return lognormal mean
        K_STATS_Lognormal_Mean = MeanValue
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Mean = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Mean: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Mean = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_Variance( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_Variance
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the arithmetic variance of a lognormal distribution.
'
' WORKSHEET EQUIVALENT
'   None native. Equivalent to (EXP(StdDevLog^2) - 1) * EXP(2*MeanLog + StdDevLog^2).
'
' PROVENANCE
'   Standard closed-form lognormal second central moment. Not proprietary.
'
' INPUTS
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'
' RETURNS
'   Variant
'     Success => (Exp(StdDevLog^2) - 1) * Exp(2 * MeanLog + StdDevLog^2).
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' ERROR POLICY
'   - Invalid parameters return CVErr(xlErrNum).
'   - Overflow of either exponential or of the product returns CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'
' DEPENDENCIES
'   - PROB_ValidateLogParameters
'   - PROB_TryExp
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim VarianceLog         As Double          'Variance of Log(X)
    Dim ExpVar              As Double          'Exp(VarianceLog)
    Dim ExpShift            As Double          'Exp(2*MeanLog + VarianceLog)
    Dim Factor              As Double          'Exp(VarianceLog) - 1
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE VARIANCE
'------------------------------------------------------------------------------
    'Compute log variance
        VarianceLog = StdDevLog * StdDevLog
    'Exponentiate both terms with explicit overflow detection
        If Not PROB_TryExp(VarianceLog, ExpVar) Then
            FailMsg = "Lognormal variance overflows Double range"
            GoTo Fail_Num
        End If

        If Not PROB_TryExp(2# * MeanLog + VarianceLog, ExpShift) Then
            FailMsg = "Lognormal variance overflows Double range"
            GoTo Fail_Num
        End If
    'Guard the product against overflow before multiplying
        Factor = ExpVar - 1#

    'Nested rather than And-ed: VBA's And is not short-circuit, so a single-line
    'test would evaluate PROB_DOUBLE_MAX / ExpShift even when ExpShift has
    'underflowed to zero, raising run-time error 11 on a valid input
        If ExpShift > 0# Then
            If Factor > PROB_DOUBLE_MAX / ExpShift Then
                FailMsg = "Lognormal variance overflows Double range"
                GoTo Fail_Num
            End If
        End If
    'Return lognormal variance
        K_STATS_Lognormal_Variance = Factor * ExpShift
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_Variance = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_Variance: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_Variance = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_StdDev( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_StdDev
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the arithmetic standard deviation of a lognormal distribution.
'
' WHY THIS EXISTS
'   Callers frequently need the arithmetic standard deviation directly (for
'   example to recover an input StdDev after a parameter conversion) rather than
'   taking the square root of the variance themselves.
'
' WORKSHEET EQUIVALENT
'   None native. Equal to SQRT of the lognormal variance.
'
' PROVENANCE
'   Standard closed-form result, computed as Sqr(Exp(StdDevLog^2) - 1) *
'   Exp(MeanLog + 0.5 * StdDevLog^2). This reduced-magnitude arrangement uses a
'   smaller exponent than Sqr(Variance) and therefore overflows later.
'   Not proprietary.
'
' INPUTS
'   MeanLog
'     Mean of Log(X).
'
'   StdDevLog
'     Standard deviation of Log(X).
'
' RETURNS
'   Variant
'     Success => Sqr(Exp(StdDevLog^2) - 1) * Exp(MeanLog + 0.5 * StdDevLog^2).
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' ERROR POLICY
'   - Invalid parameters return CVErr(xlErrNum).
'   - Overflow of either exponential or of the product returns CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'
' DEPENDENCIES
'   - PROB_ValidateLogParameters
'   - PROB_TryExp
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim VarianceLog         As Double          'Variance of Log(X)
    Dim ExpVar              As Double          'Exp(VarianceLog)
    Dim ExpShift            As Double          'Exp(MeanLog + 0.5*VarianceLog)
    Dim Factor              As Double          'Sqr(Exp(VarianceLog) - 1)
    Dim FailMsg             As String          'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate lognormal parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then GoTo Fail_Num
'------------------------------------------------------------------------------
' COMPUTE STANDARD DEVIATION
'------------------------------------------------------------------------------
    'Compute log variance
        VarianceLog = StdDevLog * StdDevLog
    'Exponentiate both terms with explicit overflow detection
        If Not PROB_TryExp(VarianceLog, ExpVar) Then
            FailMsg = "Lognormal standard deviation overflows Double range"
            GoTo Fail_Num
        End If

        If Not PROB_TryExp(MeanLog + 0.5 * VarianceLog, ExpShift) Then
            FailMsg = "Lognormal standard deviation overflows Double range"
            GoTo Fail_Num
        End If
    'Square-root factor (ExpVar >= 1 since StdDevLog > 0)
        Factor = Sqr(ExpVar - 1#)
    'Guard the product against overflow before multiplying
    'Nested rather than And-ed: VBA's And is not short-circuit, so a single-line
    'test would evaluate PROB_DOUBLE_MAX / ExpShift even when ExpShift has
    'underflowed to zero, raising run-time error 11 on a valid input
        If ExpShift > 0# Then
            If Factor > PROB_DOUBLE_MAX / ExpShift Then
                FailMsg = "Lognormal standard deviation overflows Double range"
                GoTo Fail_Num
            End If
        End If
    'Return lognormal standard deviation
        K_STATS_Lognormal_StdDev = Factor * ExpShift
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_StdDev = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_StdDev: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_StdDev = CVErr(xlErrValue)
End Function


Public Function K_STATS_Lognormal_ParametersFromMeanStdDev( _
    ByVal Mean As Double, _
    ByVal StdDev As Double, _
    Optional ByRef Status As String = "") _
    As Variant
'
'==============================================================================
' K_STATS_Lognormal_ParametersFromMeanStdDev
'------------------------------------------------------------------------------
' PURPOSE
'   Converts arithmetic lognormal mean and standard deviation into log-space
'   parameters.
'
' WHY THIS EXISTS
'   Market and risk inputs are often expressed as arithmetic mean and standard
'   deviation of X, while the lognormal density requires MeanLog and StdDevLog
'   for Log(X).
'
' WORKSHEET EQUIVALENT
'   None native. Custom method-of-moments inversion.
'
' PROVENANCE
'   Standard method-of-moments formulas for the lognormal. Not proprietary.
'
' INPUTS
'   Mean
'     Arithmetic mean of X.
'     Must be strictly positive.
'
'   StdDev
'     Arithmetic standard deviation of X.
'     Must be strictly positive.
'
' RETURNS
'   Variant
'     Success => 1 x 2 Variant array:
'                  [1,1] = MeanLog
'                  [1,2] = StdDevLog
'     Failure => CVErr(xlErrNum) or CVErr(xlErrValue).
'
' BEHAVIOR
'   - Validates strictly positive Mean and StdDev.
'   - Computes:
'       StdDevLog = Sqr(Log(1 + StdDev^2 / Mean^2))
'       MeanLog   = Log(Mean) - 0.5 * StdDevLog^2
'
' NOTE
'   StdDev = 0 is rejected: a degenerate (point-mass) lognormal has StdDevLog = 0,
'   which every density/cumulative/inverse routine rejects. Requiring a strictly
'   positive StdDev keeps the produced parameters usable downstream.
'
' ERROR POLICY
'   - Invalid numeric domains return CVErr(xlErrNum).
'   - Unexpected runtime errors return CVErr(xlErrValue).
'   - Detailed diagnostic messages are written to Status (status bar only when
'     PROB_WRITE_STATUS_BAR is True).
'
' DEPENDENCIES
'   - PROB_IsFinite
'   - PROB_SetStatus
'
' UPDATED
'   2026-07-08
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Result(1 To 1, 1 To 2) As Double       'Output parameter row
    Dim VarianceRatio          As Double       'StdDev^2 / Mean^2
    Dim VarianceLog            As Double       'Variance of Log(X)
    Dim FailMsg                As String       'Detailed failure message
'------------------------------------------------------------------------------
' INITIALIZE
'------------------------------------------------------------------------------
    'Route unexpected runtime errors to the error handler
        On Error GoTo Err_Handler
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Initialize the failure message buffer
        FailMsg = vbNullString
'------------------------------------------------------------------------------
' VALIDATE INPUTS
'------------------------------------------------------------------------------
    'Validate arithmetic mean
        If Not PROB_IsFinite(Mean) Or Mean <= 0# Then
            FailMsg = "Mean must be a finite strictly positive number"
            GoTo Fail_Num
        End If
    'Validate arithmetic standard deviation (strictly positive)
        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            GoTo Fail_Num
        End If
'------------------------------------------------------------------------------
' COMPUTE LOGNORMAL PARAMETERS
'------------------------------------------------------------------------------
    'Compute variance ratio
        VarianceRatio = (StdDev * StdDev) / (Mean * Mean)
    'Compute log variance
        VarianceLog = Log(1# + VarianceRatio)
    'Populate output parameters
        Result(1, 2) = Sqr(VarianceLog)
        Result(1, 1) = Log(Mean) - 0.5 * VarianceLog
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return 1 x 2 parameter row
        K_STATS_Lognormal_ParametersFromMeanStdDev = Result
    'Clear diagnostic status
        PROB_SetStatus Status, vbNullString
    'Exit before failure and error-handler blocks
        Exit Function
'------------------------------------------------------------------------------
' FAIL - NUMERIC
'------------------------------------------------------------------------------
Fail_Num:
    'Write diagnostics
        PROB_SetStatus Status, FailMsg
    'Return worksheet numeric error
        K_STATS_Lognormal_ParametersFromMeanStdDev = CVErr(xlErrNum)
    'Exit before the error handler
        Exit Function
'------------------------------------------------------------------------------
' ERROR HANDLER
'------------------------------------------------------------------------------
Err_Handler:
    'Write unexpected runtime errors to diagnostics
        PROB_SetStatus Status, "Unexpected error in K_STATS_Lognormal_ParametersFromMeanStdDev: " & Err.Description
    'Return worksheet value error
        K_STATS_Lognormal_ParametersFromMeanStdDev = CVErr(xlErrValue)
End Function


'==============================================================================
' PRIVATE NUMERICAL KERNELS
'==============================================================================

Private Function PROB_NormalPDF( _
    ByVal Z As Double) _
    As Double
'
'==============================================================================
' PROB_NormalPDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal density using a fast Double-to-Double contract.
'
' PROVENANCE
'   Closed-form density. Not proprietary.
'==============================================================================
'
'------------------------------------------------------------------------------
' COMPUTE
'------------------------------------------------------------------------------
    'Protect against numerical underflow in the extreme tails
        If Abs(Z) > PROB_PDF_TAIL_CUTOFF Then
            PROB_NormalPDF = 0#
        Else
            PROB_NormalPDF = PROB_INV_SQRT_TWO_PI * Exp(-0.5 * Z * Z)
        End If
End Function


Private Function PROB_NormalCDF( _
    ByVal Z As Double) _
    As Double
'
'==============================================================================
' PROB_NormalCDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the standard normal cumulative distribution function.
'
' METHOD / PROVENANCE
'   Hart rational + continued-fraction approximation (Hart 1968), double-
'   precision arrangement popularised by Graeme West (Wilmott, 2009). Public.
'   Accurate to approximately 1E-15.
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim Y                   As Double          'Absolute z value
    Dim Exponential         As Double          'Exp(-0.5 * Y^2)
    Dim SumA                As Double          'Numerator accumulator
    Dim SumB                As Double          'Denominator accumulator
    Dim TailProbability     As Double          'Lower-tail probability for |Z|
'------------------------------------------------------------------------------
' COMPUTE
'------------------------------------------------------------------------------
    'Work with absolute value
        Y = Abs(Z)
    'Handle extreme tails directly
        If Y > PROB_CDF_TAIL_CUTOFF Then
            If Z > 0# Then
                PROB_NormalCDF = 1#
            Else
                PROB_NormalCDF = 0#
            End If

            Exit Function
        End If
    'Compute exponential term
        Exponential = Exp(-0.5 * Y * Y)
    'Use rational approximation in main region
        If Y < PROB_CDF_SPLIT Then
            SumA = 3.52624965998911E-02 * Y + 0.700383064443688
            SumA = SumA * Y + 6.37396220353165
            SumA = SumA * Y + 33.912866078383
            SumA = SumA * Y + 112.079291497871
            SumA = SumA * Y + 221.213596169931
            SumA = SumA * Y + 220.206867912376

            SumB = 8.83883476483184E-02 * Y + 1.75566716318264
            SumB = SumB * Y + 16.064177579207
            SumB = SumB * Y + 86.7807322029461
            SumB = SumB * Y + 296.564248779674
            SumB = SumB * Y + 637.333633378831
            SumB = SumB * Y + 793.826512519948
            SumB = SumB * Y + 440.413735824752

            TailProbability = Exponential * SumA / SumB
    'Use continued-fraction approximation in far tail
        Else
            SumA = Y + 0.65
            SumA = Y + 4# / SumA
            SumA = Y + 3# / SumA
            SumA = Y + 2# / SumA
            SumA = Y + 1# / SumA

            TailProbability = Exponential / (SumA * PROB_SQRT_TWO_PI)
        End If
    'Reflect according to the sign of Z
        If Z > 0# Then
            PROB_NormalCDF = 1# - TailProbability
        Else
            PROB_NormalCDF = TailProbability
        End If
End Function


Private Function PROB_NormalInvCDF( _
    ByVal Probability As Double) _
    As Double
'
'==============================================================================
' PROB_NormalInvCDF
'------------------------------------------------------------------------------
' PURPOSE
'   Returns the inverse standard normal cumulative distribution function at
'   machine precision (~1E-15).
'
' METHOD / PROVENANCE
'   Peter J. Acklam's rational approximation (public, released freely), taken
'   from the shared kernel PROB_NormalInvCDFRaw in M_STATS_CORE, refined by a
'   single Halley iteration. Acklam alone gives ~1.15E-9 relative error; the
'   Halley step, using the double-precision PROB_NormalCDF/PROB_NormalPDF, lifts
'   accuracy to ~1E-15.
'
'   The Halley update, for F = CDF, f = PDF, on solving F(x) = p:
'       e = F(x) - p
'       u = e / f(x)
'       x <- x - u / (1 + x * u / 2)
'   The refinement is skipped when f(x) has underflowed to 0, and when F(x) has
'   saturated to 0 or 1 beyond PROB_CDF_TAIL_CUTOFF; in both cases the raw Acklam
'   estimate is already the best available.
'
' ACCURACY
'   Relative error below 5E-16 for Probability in [0.001, 0.999]. Beyond the
'   z = PROB_CDF_SPLIT (7.07) branch of PROB_NormalCDF the achievable accuracy is
'   bounded by the RELATIVE accuracy of that CDF in its tail, which is about
'   1E-10; the Hart/West arrangement is 1E-15 in ABSOLUTE terms, not relative.
'   Tail quantiles therefore carry roughly 1E-10 relative error, not 1E-15.
'
' PRECONDITION
'   Probability must be strictly between 0 and 1.
'==============================================================================
'
'------------------------------------------------------------------------------
' DECLARE
'------------------------------------------------------------------------------
    Dim X                   As Double          'Acklam estimate / refined root
    Dim PdfX                As Double          'Density at the estimate
    Dim CdfX                As Double          'Cumulative probability at the estimate
    Dim E                   As Double          'CDF(X) - Probability
    Dim U                   As Double          'Newton correction e / pdf
'------------------------------------------------------------------------------
' STARTING ESTIMATE
'------------------------------------------------------------------------------
    'Raw Acklam rational approximation (shared kernel, M_STATS_CORE)
        X = PROB_NormalInvCDFRaw(Probability)
'------------------------------------------------------------------------------
' HALLEY REFINEMENT
'------------------------------------------------------------------------------
    'Evaluate the density and the cumulative probability at the estimate
        PdfX = PROB_NormalPDF(X)
        CdfX = PROB_NormalCDF(X)

    'Refine only where the density has not underflowed AND the CDF has not
    'saturated. Past Abs(X) = PROB_CDF_TAIL_CUTOFF the CDF returns exactly 0 or 1,
    'so the residual degenerates to -Probability and the step actively degrades
    'the estimate: at Probability = 1E-300 it turns a 9.7E-11 relative error into
    '4.9E-04. Where the CDF has saturated, the raw Acklam value is the best
    'available answer.
        If PdfX > 0# And CdfX > 0# And CdfX < 1# Then
            E = CdfX - Probability
            U = E / PdfX
            X = X - U / (1# + X * U / 2#)
        End If
'------------------------------------------------------------------------------
' RETURN RESULT
'------------------------------------------------------------------------------
    'Return the refined quantile
        PROB_NormalInvCDF = X
End Function


'==============================================================================
' PRIVATE VALIDATION HELPERS
'==============================================================================

Private Function PROB_ValidateNormalInputs( _
    ByVal X As Double, _
    ByVal Mean As Double, _
    ByVal StdDev As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateNormalInputs
'------------------------------------------------------------------------------
' PURPOSE
'   Validates inputs for a normal distribution with mean and standard deviation.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate X
        If Not PROB_IsFinite(X) Then
            FailMsg = "X must be a finite number"
            Exit Function
        End If
    'Validate mean
        If Not PROB_IsFinite(Mean) Then
            FailMsg = "Mean must be a finite number"
            Exit Function
        End If
    'Validate standard deviation
        If Not PROB_IsFinite(StdDev) Or StdDev <= 0# Then
            FailMsg = "StdDev must be a finite strictly positive number"
            Exit Function
        End If
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateNormalInputs = True
End Function


Private Function PROB_ValidateLognormalInputs( _
    ByVal X As Double, _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateLognormalInputs
'------------------------------------------------------------------------------
' PURPOSE
'   Validates inputs for lognormal density calculations.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate evaluation point
        If Not PROB_IsFinite(X) Or X <= 0# Then
            FailMsg = "X must be a finite strictly positive number"
            Exit Function
        End If
    'Validate log-space parameters
        If Not PROB_ValidateLogParameters(MeanLog, StdDevLog, FailMsg) Then Exit Function
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateLognormalInputs = True
End Function


Private Function PROB_ValidateLogParameters( _
    ByVal MeanLog As Double, _
    ByVal StdDevLog As Double, _
    ByRef FailMsg As String) _
    As Boolean
'
'==============================================================================
' PROB_ValidateLogParameters
'------------------------------------------------------------------------------
' PURPOSE
'   Validates log-space lognormal parameters.
'==============================================================================
'
'------------------------------------------------------------------------------
' VALIDATE
'------------------------------------------------------------------------------
    'Validate log mean
        If Not PROB_IsFinite(MeanLog) Then
            FailMsg = "MeanLog must be a finite number"
            Exit Function
        End If
    'Validate log standard deviation
        If Not PROB_IsFinite(StdDevLog) Or StdDevLog <= 0# Then
            FailMsg = "StdDevLog must be a finite strictly positive number"
            Exit Function
        End If
'------------------------------------------------------------------------------
' RETURN SUCCESS
'------------------------------------------------------------------------------
    'Return success
        PROB_ValidateLogParameters = True
End Function




